routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('calculate-cart-shipping-cost', 'FrontController@calculateCartShippingCost');

Route::get('/scalapay/success', 'FrontController@scalapayRedirectSuccess')->name('scalapayRedirectSuccess');
Route::get('/scalapay/fail', 'FrontController@scalapayRedirectFail')->name('scalapayRedirectFail');

Route::get('/ideal', 'FrontController@idealRedirect')->name('idealRedirect');


Route::get('/donut/flip', 'FrontController@donut')->name('donut');


Route::get('artisan/import-productgroups', 'FrontController@scoutImportProductgroups');

Route::get('download-xlsx-with-product-translations', 'TranslationsController@downloadXlsxWithProductTranslations');

Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});


Route::get('/', 'FrontController@mainRedirect');


Route::get('/thumbs/dropzone/{filename}', 'ImageResizeController@thumbs')->where(["filename" => ".*"]);

Route::get('/ir/{size?}/{filename}', 'ImageResizeController@resize')->where(["filename" => ".*"])->name('ir');

Route::get('search-results','FrontController@searchResults');
Route::get('{locale}/pg','FrontController@productGrid')->name('productGrid');

Route::get('{locale}/p/{name}/{id}','FrontController@productPage')->name('productPage');
Route::get('{locale}/a/{name}/{id}', 'FrontController@articlePage')->name('articlePage');
Route::get('{locale}/shops', 'FrontController@shops')->name('shops');
Route::get('{locale}/about-us', 'FrontController@aboutUs')->name('aboutUs');

Route::get('/test','TestController@index');

Route::get('add-to-cart', 'FrontController@addToCart')->name('addToCart');
Route::post('remove-from-cart', 'FrontController@removeFromCart')->name('removeFromCart');

Route::get('{locale}/add-discount-code/{code?}', 'FrontController@addDiscountCode')->name('addDiscountCode');
Route::post('remove-discount-code', 'FrontController@removeDiscountCode')->name('removeDiscountCode');

Route::get('{locale}/cart', 'FrontController@cart')->name('cart');

Route::get('{locale}/thank-you-page-ecommerce-cart/{lead_id}/{value}', 'FrontController@thankYouPageEcommerceCart')->name('thankYouPageEcommerceCart');
Route::get('{locale}/payment-failed/', 'FrontController@paymentFailed')->name('paymentFailed');

Route::post('confirm-cart', 'FrontController@confirmCart')->name('confirmCart');

Route::post('subscribe-newsletter', 'FrontController@subscribeNewsletter')->name('subscribeNewsletter');
Route::get('{locale}/thank-you-page-newsletter-subscription', 'FrontController@thankYouPageNewsletterSubscription')->name('thankYouPageNewsletterSubscription');

Route::get('{locale?}', 'FrontController@home')->name('home');

Route::get('login/facebook', 'FrontController@FacebookLoginRedirectToProvider')->name('FacebookLoginRedirectToProvider');
Route::get('login/facebook/callback', 'FrontController@FacebookLoginCallbackHandler')->name('FacebookLoginCallbackHandler');


Route::get('admin/shippings-manager/{id}','ShippingsManager@show')->name('shippingsManager');
Route::post('admin/shippings-manager/','ShippingsManager@store')->name('shippingsManagerStore');

Route::post('media-dropzone', 'DropzoneController@handleDropzoneUpload');

Route::post('toggle-boolean','CustomFieldsController@toggleBoolean')->name('toggleBoolean');

Route::get('related-products-to-product/{product_id}/{user_id}/{how_many_products}', 'FrontController@relatedProductsToProduct')->name('relatedProductsToProduct');

Route::post('/functions/cache-cart-field', 'FrontController@cacheCartfield')->name('cacheCartField');

Route::post('/functions/track-event', 'FrontController@trackEvent')->name('trackEvent');

#Route::post('ping-lead-validity', 'FrontController@checkLeadValidiy')->name('checkLeadValidiy');
Route::post('ping-lead-validity', function(){return 1;})->name('checkLeadValidiy');

app/Models/Product.php
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Model;
use App\Models\Manufacturer;
use App\Models\Category;
use App\Models\Shippingrule;
use App\Models\Attributevalue;
use App\Models\Productgroup;
use App\Models\Warehouseavailability;
use App\Traits\Helpers;
use Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations;
use Str;
use App;
use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use CrudTrait;
    use HasTranslations;
    use Helpers;
    use Searchable;
    use SoftDeletes;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'products';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];
    protected $casts = ['photos' => 'array'];
    public $translatable = ['name', 'short_description','description','extended_description'];



    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    public function revertPrice(){
        $this->price = $this->compare_price;
        $this->saveWithoutEvents();
    }

    public function getShortDescription($limit = 100){
        $ellipsis = '...';
        return (!is_null($this->short_description) && $this->short_description != '') ? $this->short_description : Str::limit(strip_tags($this->description),$limit, $ellipsis);
    }

    public function getSiblings(){
        if(is_object($this->group)){
            $groups = Productgroup::whereExtIdForSiblings($this->group->ext_id_for_siblings)->where('id','!=',$this->group->id)->get();
            $return = collect([]);
            if(!is_null($groups)){
                foreach($groups as $group){
                    $return->push($group->product);
                }
                return collect($return->filter()->all());
            }
        }

        return collect([]);

    }

    public function variants(){
        return Product::where('productgroup_id',$this->productgroup_id)->get();
    }

    public function shouldBeSearchable()
    {
        return true;
        #return ($this->enabled && !is_null($this->category));
    }

    public function getShippingCost(){

        $weight = (!is_null($this->packaging_weight)) ? $this->packaging_weight : $this->product_weight ;

        if(!is_null($weight)){
            $shippingRule = Shippingrule::whereRaw('weight_from <= ' . $weight . ' AND weight_to >' . $weight)->first();
            if (!is_null($shippingRule)) {
                return $shippingRule->price;
            }
        }

        return 0;

    }

    public function collections(){
        return $this->belongsToMany(Collection::class);
    }

    public function cover($size = 'h480'){

        $cover = (!is_null($this->photos)) ? collect($this->photos)->first() : null;

        if (!is_null($cover)) {
            $cover =  url(Route('ir', ['size' => $size, 'filename' => $cover], false));
            return $cover;
        }

        return null;

    }

    public function pdfCover($size = 'h480')
    {

        $cover = (!is_null($this->group->product->photos)) ? collect($this->group->product->photos)->first() : null;

        if (!is_null($cover)) {
            return asset($cover);
        }

        return null;
    }

    public function secondCover($size = 'h480'){
        $cover = $this->cover($size);
        $secondCover = (collect($this->photos)->count() > 1) ? collect($this->photos)->get(1) : $cover;
        $secondCover =  Route('ir', ['size' => $size, 'filename' => $secondCover], false);
        return $secondCover;
    }

    public function toSearchableArray()
    {

        App::setLocale('it');

        $attributes = [];

        $attrs = $this->attributevalues;

        $locales = array_keys(config('backpack.crud.locales'));

        foreach($locales as $locale){

            $array['name_'. $locale] = $this->getTranslation('name', $locale);
            $array['description_'. $locale] = $this->getTranslation('description', $locale);
            $array['short_description_'. $locale] = $this->getTranslation('short_description', $locale);
            $array['category_'. $locale] = $this->category->getTranslation('name', $locale);
            $array['url_'.$locale] = $this->makeUrl($locale);

            if ($attrs->count() > 0) {
                foreach ($attrs as $attr) {
                    $array[$attr->attribute->name.'_'.$locale] = $attr->getTranslation('name', $locale);
                }
            }

            if(!is_null($this->gender)){
                $array['gender_' . $locale] = $this->gender->getTranslation('name', $locale);
            }

            $array['attributes_line_' . $locale] = $this->getAttrbutesLine($locale);

        }

        $array['sku'] = $this->sku;
        $array['brand'] = (!is_null($this->manufacturer)) ? $this->manufacturer->name : '';
        $array['price'] = $this->price;

        $cover = (!is_null($this->photos)) ? collect($this->photos)->first() : null;
        if(!is_null($cover)){
            $cover =  Route('ir', ['size' => 'h480', 'filename' => $cover],false);
        }

        $array['cover'] = $cover;




        // Applies Scout Extended default transformations:
        //$array = $this->transform($array);

        return $array;
    }

    public function addAttribute($attribute, $value, $cfg = [])
    {
        $attribute = trim(Str::lower(str_replace('_', ' ', $attribute)));
        $value = trim(Str::lower(str_replace('_', ' ', $value)));
        $locale = (isset($cfg['locale'])) ? $cfg['locale'] : 'it';
        App::setLocale($locale);
        if($attribute != '' && $value != ''){
            $attrObj = Attribute::whereRaw("JSON_EXTRACT(name, '$.".$locale."') = '". addslashes($attribute)."'")->first();
            if(is_null($attrObj)){
                $attrObj = Attribute::create(['name' => $attribute]);
            }
            $attributeValueObj = AttributeValue::whereRaw("JSON_EXTRACT(name, '$.".$locale."') = '".addslashes($value). "' AND attribute_id = ". $attrObj->id)->first();
            if (is_null($attributeValueObj)) {
                $attributeValueObj = AttributeValue::create(['name' => $value,'attribute_id' => $attrObj->id]);
            }
            $this->attributevalues()->syncWithoutDetaching($attributeValueObj->id);
            $this->save();
        }
    }

    public function groupName(){
        if(!is_null($this->group)){
            if($this->group->name != '')
                return $this->group->name;
            return $this->group->id;
        }
        return 'Nessun gruppo';

    }

    public function getQuantityByWarehouseId($warehouseId)
    {
        $warehouseavailabilities = $this->warehouseavailabilities->keyBy('warehouse_id');
        return (isset($warehouseavailabilities[$warehouseId]['quantity'])) ? $warehouseavailabilities[$warehouseId]['quantity'] : 0;
    }

    public function setQuantityByWarehouseId($warehouseId,$quantity,$reason = ''){
        $currentQuantity = $this->getQuantityByWarehouseId($warehouseId);
        if($quantity != $currentQuantity){
            $diff = $quantity - $currentQuantity;
            $this->stockoperations()->create([
                'sign' => ($quantity > $currentQuantity) ? 1 : -1,
                'quantity' => abs($diff),
                'warehouse_id' => $warehouseId,
                'description' => $reason
            ]);
        }
    }


    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    public function discountcodes(){
        return $this->belongsToMany(Discountcode::class);
    }

    public function gender(){
        return $this->belongsTo(Gender::class);
    }

    public function printGooglecategoryBreadcrumb()
    {
        return collect($this->category->googlecategory->ancestors->pluck('name'))->push($this->category->googlecategory->name)->implode(' > ');
    }

    public function warehouseavailabilities(){
        return $this->hasMany(Warehouseavailability::class);
    }


    public function manufacturer(){
        return $this->belongsTo(Manufacturer::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function attributevalueextensiongroup(){
        return $this->belongsTo(Attributevalueextensiongroup::class);
    }

    public function attributevalues()
    {
        return $this->belongsToMany(Attributevalue::class);
    }

    public function group(){
        return $this->belongsTo(Productgroup::class,'productgroup_id');
    }

    public function productgroup()
    {
        return $this->belongsTo(Productgroup::class, 'productgroup_id');
    }

    public function stockoperations(){
        return $this->hasMany(Stockoperation::class);
    }

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */

    public function getDiscountPercentageAttribute(){
        $product = $this;
        if($product->compare_price > 0){
            $discount = $product->compare_price - $product->price;
            $discountPercentage = $discount *  100 / $product->compare_price;
            return round($discountPercentage);
        }

resources/views/made/about_us.blade.php
@extends(env('THEME_NAME').'.main')
@section('content')

<section class="page-banner banner-02 bg_cover" style="background-image: url({{ asset('resources/'.env('THEME_NAME').'/about-us-background.jpg') }});">
        <div class="container">
            <div class="page-banner-content text-center">
                <h2 class="title text-white text-shadow">Madé Firenze</h2>
                <ol class="breadcrumb justify-content-center text-white">
                    <li class="breadcrumb-item"><a class="text-white" href="{{ url($locale) }}">Home</a></li>
                    <li class="breadcrumb-item active text-white">@lang('all.about')</li>
                </ol>
            </div>
        </div>
    </section>

<section class="about-area pt-50">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="about-content mt-45">
                        <h2 class="title">@lang('all.welcome to') Madé Firenze</h2>
                        <p class="text-help">
                            <i>— “Un brivido a fior di pelle in perfetto stile italiano”</i>
                        </p>
                        <p>
                            MF (Madè Firenze) nasce dall’incontro tra la passione di Ilaria Iemmi (Creative Director) e lo spirito imprenditoriale di Marco Matteini (CEO). <br>
                            Il nome identifica lo spirito del marchio, <b>legato al territorio di origine con originalità ed innovazione</b>, in un’espressione di italianità decisamente internazionale.<br>
                            Obbiettivo della casa Fiorentina è quello di far si che le donne si possano riconoscere in un brand giovane e dinamico, ideato per un quotidiano decisamente glamour. <br>
                            Abbandonato il superato concetto di donna fashionista  MADE’ FIRENZE si propone ad una donna completa: dinamica, romantica e femminile. <br>
                            In una parola, una donna moderna, che si distingue non solo perché al passo coi tempi ma perché esprime senza filtri la sua autenticità. La sua vera identità. <br>
                            I nostri valori? <br>
                            <b>
                            Qualità, ricercatezza, innovazione, italianità, versatilità ed emozione.
                            </b> <br>
                            I modelli esprimono il concetto di eleganza, unicita’ e qualita’. <br>
                            I punti fondamentali per chi ama i dettagli racchiusi nel <b>Made in Italy</b> che fanno dell’accessorio, un prodotto di <b> stile ed eccellenza.</b>
                        </p>
                        <div class="about-signature">
                            <img src="resources/{{ env('THEME_NAME') }}/ceo.png" alt="" class="w-100">
                            <p>Ilaria Iemmi</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-image mt-50">
                        <img src="/resources/{{ env('THEME_NAME') }}/about-us.jpg" alt="">
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="about-area pt-50">
        <div class="container">
            <div class="row  align-items-center">

                <div class="col-lg-6">
                    <div class="about-image mt-50">
                        <img src="/resources/{{ env('THEME_NAME') }}/about-us-2.jpg" alt="">
                    </div>
                </div>
                 <div class="col-lg-6">
                    <div class="about-content mt-45">
                        <h2 class="title">Sara Di Vaira</h2>
                        <p>
                            <b>Sara Di Vaira</b> STAR televisiva, ballerina e vincitrice 2019 del programma TV RAI <b>“Ballando con le Stelle”</b> rappresenta la DONNA “MADE’ FIRENZE” come Testimonial del brand.<br>La scelta di Sara come Testimonial nasce da una perfetta armonia di Bellezza, Semplicità, Freschezza, Vitalità, Femminilità, Personalità, Sportività e Solarità che la contraddistinguono.<br>“LA PIU’ AMATA DAGLI ITALIANI!!!<br>Tutte caratteristiche che troviamo all’interno delle borse del brand “Made’ Firenze” e che ne fanno un punto di forza particolarmente stimolante.<br>Ci rivolgiamo a tutte le Donne, con un concetto di “Moda Non Moda” perchè oggi la Donna ama distinguersi, stupire… e indossare creazioni uniche, belle e di qualità.<br> Made’ Firenze ha saputo cogliere questo messaggio creando collezioni in semplicità, pezzi quasi unici, dai dettagli preziosi e dal mood senza tempo.<br>Rappresentiamo con orgoglio un azienda con un forte legame al territorio di origine (Firenze – Italia), alla scrupolosa scelta dei materiali, dei dettagli, di una produzione 100% made in Italy, che guarda al futuro creando in ecosostenibilità le proprie borse. <br><br> “Se le Stelle staranno  a guardare, noi ci metteremo a ballare!” <br><i>(Cit. Ilaria iemmi)</i>
                        </p>
                        <div class="about-signature">

                            {{-- <p>Ilaria Iemmi</p>  --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @hss('100')
    {{--
   <section class="team-area pt-110">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="section-title text-center pb-30">
                        <h2 class="title">@lang('all.our team')</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-12 offset-md-3">
                    <div class="single-team text-center mt-30">
                        <div class="team-image">
                            <img src="/assets/images/harris/bruno.png" alt="">
                        </div>
                        <div class="team-content">
                            <h5 class="name"><a href="#">Ilaria Iemmi</a></h5>
                            <span class="designation">Fashion Designer</span>

                            <ul class="social">
                                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                                <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                <li><a href="#"><i class="fal fa-envelope"></i></a></li>
                            </ul>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-12">
                    <div class="single-team text-center mt-30">
                        <div class="team-image">
                            <img src="/assets/images/harris/jari.png" alt="">
                        </div>
                        <div class="team-content">
                            <h5 class="name"><a href="#">Marco Matteini</a></h5>
                            <span class="designation">CEO</span>

                        </div>
                    </div>
                </div>


            <div class="col-lg-3 col-sm-12">
                    <div class="single-team text-center mt-30">
                        <div class="team-image">
                            <img src="/assets/images/harris/angela.png" alt="">
                        </div>
                        <div class="team-content">
                            <h5 class="name"><a href="#">Angela Bambusa</a></h5>
                            <span class="designation">CFO/ Chief Financial Officer</span>

                        </div>
                    </div>
                </div>
                  <div class="col-lg-3 col-sm-12">
                    <div class="single-team text-center mt-30">
                        <div class="team-image">
                            <img src="/assets/images/harris/maila.png" alt="">
                        </div>
                        <div class="team-content">
                            <h5 class="name"><a href="#">Maila Famiglietti</a></h5>
                            <span class="designation">CIO/ Chief Information Officer</span>

                        </div>
                    </div>
                </div>



            </div>
            @hss('100')
        </div>
    </section>
     --}}
{{--
    <div class="brand-logo-area border-0 pt-75 pb-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="section-title text-center pb-30">
                        <h2 class="title">OUR PARTNERS</h2>
                    </div>
                </div>
            </div>
            <div class="brand-row brand-active slick-initialized slick-slider">
                <div class="slick-list draggable"><div class="slick-track" style="opacity: 1; width: 1200px; transform: translate3d(0px, 0px, 0px);"><div class="brand-col slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" tabindex="0" style="width: 240px;">
                    <div class="single-brand-2 mt-30">
                        <img src="assets/images/brand-1.png" alt="brand">
                    </div>
                </div><div class="brand-col slick-slide slick-active" data-slick-index="1" aria-hidden="false" tabindex="0" style="width: 240px;">
                    <div class="single-brand-2 mt-30">
                        <img src="assets/images/brand-2.png" alt="brand">
                    </div>
                </div><div class="brand-col slick-slide slick-active" data-slick-index="2" aria-hidden="false" tabindex="0" style="width: 240px;">
                    <div class="single-brand-2 mt-30">
                        <img src="assets/images/brand-3.png" alt="brand">
                    </div>
                </div><div class="brand-col slick-slide slick-active" data-slick-index="3" aria-hidden="false" tabindex="0" style="width: 240px;">
                    <div class="single-brand-2 mt-30">
                        <img src="assets/images/brand-4.png" alt="brand">
                    </div>
                </div><div class="brand-col slick-slide slick-active" data-slick-index="4" aria-hidden="false" tabindex="0" style="width: 240px;">
                    <div class="single-brand-2 mt-30">
                        <img src="assets/images/brand-5.png" alt="brand">
                    </div>
                </div></div></div>




            </div>
        </div>
    </div>
 --}}
@endsection

resources/views/made/article.blade.php
@extends(env('THEME_NAME').'.main')
@section('content')
    @hss('190')
          @if (!is_null($article->cover) && $article->cover != '')
            <section class="page-banner bg_cover" style="background-image: url('{{ Route('ir',['size' => 'h1600','filename' =>  $article->cover ])}}');">
        @else
                @hss('300')
        @endif
        <div class="container">
            <div class="page-banner-content text-center">
                @hss('100')
                <h2 class="title text-white"  >{{ $article->name  }}</h2>
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item "><a class="text-white" href="/">Home</a></li>
                </ol>
                @hss('100')
            </div>
        </div>
    </section>

<section class="blog-page pt-20 pb-120">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="single-blog mt-80">
                        <div class="blog-image">
                            <a>
                                {{--
                                @if (!is_null($article->cover) && $article->cover != '')
                                <img src="{{ Route('ir',['size' => 'h800','filename' =>  $article->cover ])}}" alt="blog">
                                @endif
                                 --}}
                                {{--  <i class="fal fa-search-plus"></i> --}}
                            </a>
                        </div>
                        <div class="blog-content">
                            <!--<ul class="blog-category">
                                <li><a href="#">Style</a></li>
                            </ul>-->
                            <h4 class="title text-center">{{ $article->name }}</h4>
                            <!--<ul class="blog-meta">
                                <li><a href="#">By <span> Jon Smith</span></a></li>
                                <li><a href="#"><i class="fal fa-clock"></i> June 15, 2020</a></li>
                            </ul>-->
                            <div>
                                {!! $article->description !!}
                            </div>

                            @if ($article->is_contact_page)
                                @hss('100')
                                <h4 class="title text-center">@lang('all.get in touch with us fill the form')</h4>
                                <script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/shell.js"></script>
                                <script>
                                hbspt.forms.create({
                                    region: "eu1",
                                    portalId: "25158670",
                                    formId: "8bd2cf83-6b2b-4c92-ad80-636fc9f1e111"
                                });
                                </script>
                                @hss('100')
                            @endif

                            <a href="/" class="main-btn btn-block text-white">Continua con lo shopping</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/made/main.blade.php
@include(env('THEME_NAME').'.include.header')
@yield('content')
@include(env('THEME_NAME').'.include.footer')

resources/views/made/main_home.blade.php
@include(env('THEME_NAME').'.include.head')
@yield('content')
@include(env('THEME_NAME').'.include.footer')

resources/views/made/related-products.blade.php
<div class="row product-active">
    @foreach ($products as $product)


    <div class="col-md-3 col-6">
        <div class="single-product mt-50">
            <div class="product-image">
                <div class="image">
                    <img class="product-1" src="@cim(url($product->product->cover()))" alt="{{ Str::ucfirst($product->product->name) }}">
                    <img class="product-2" src="@cim(url($product->product->secondCover()))" alt="{{ Str::ucfirst($product->product->name) }}">
                    <a class="link" href="{{  $product->product->makeUrl() }}"></a>
                </div>
                @if ($product->product->price != $product->product->price_compare && $product->product->price_compare > 0)
                    <span class="discount">{{ $product->product->discount_percentage }}%</span>
                @endif
            </div>
            <div class="product-content d-flex justify-content-between">
                <div class="product-title">
                    <h4 class="title"><a href="{{ $product->product->makeUrl() }}">{{ Str::ucfirst($product->product->name) }}</a></h4>
                </div>
                <div class="product-price">
                    <span class="text-dark">
                        <b>
                            @fp($product->product->price)
                        </b>
                    </span>
                    @if ($product->product->price != $product->product->price_compare && $product->product->price_compare > 0)
                        <span class="sale-price">@fp($product->product->price_compare)</span>
                    @endif

                </div>
            </div>
        </div>
    </div>

    @endforeach
</div>